#goal definition
string endEffector
int32 yaw_joint_index
int32 pitch_joint_index
# 0: point in world frame
# 1: target frame relative to root_frame
# 2: target frame relative to root_frame single shot
int32 type
geometry_msgs/Vector3 point
string root_frame
string target_frame
bool sendToRealHardware
int32 timeout
float32 tolerance
---
#result definition
---
#feedback
float32 error