# name of the endeffector
string endeffector
# 0: position and orientation 1: position only 2: orientation only
int8 type
# the frame of the first ik target
string target_frame_1
# target position/orientation for frame in world coordinates (if applicable)
geometry_msgs/Pose pose_1
# position weight of the first ik target
int8 pos_weight_1
# the frame of the second ik target
string target_frame_2
# target position/orientation for frame in world coordinates (if applicable)
geometry_msgs/Pose pose_2
# position weight of the second ik target
int8 pos_weight_2

---
# joint names
string[] joint_names
# these are the resulting joint angles from inverse kinematics in radians
float64[] angles
