uint8 id
# six current measurements per arm board
uint16[] current
float32[] gyro_x
float32[] gyro_y
float32[] gyro_z
float32[] acc_x
float32[] acc_y
float32[] acc_z
float32 elbow_joint_angle
float32 elbow_joint_angle_setpoint
int32 elbow_agonist_setpoint
int32 elbow_antagonist_setpoint
float32 wrist_joint_angle
float32 wrist_joint_angle_setpoint
int32 wrist_agonist_setpoint
int32 wrist_antagonist_setpoint